name: Bump version of uwu package and make a release.yml

on:
  schedule:
    # every day on 12:12
    - cron: "12 12 * * *"

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install toml
      - run: python ./.github/workflows/bump_version_and_make_tag.py
