name: Bump version of uwu package and make a release.yml

on:
  issues:
    types: [opened]

#on:
#  schedule:
#    # every day on 12:12
#    - cron: "12 12 * * *"

jobs:
  bump-and-make-release:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python ./.github/workflows/bump_version_and_make_tag.py
