on:
  schedule:
    # every day on 13:12
    - cron: "12 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
